### ISSUE TITLE
在 macbook 上运行 demo 报错

### ISSUE THREAD

**Issue by meowioo** [sdcb/Sdcb.WordCloud#3]
可以帮忙看一下吗，我在 macbook 上运行您的 demo 会报错。
在第 5 行，new WordCloudOptions 的时候报的错：
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/bc44f5c5-3f47-4e5f-81b5-4a68b74e0db5">
报错截图：
<img width="577" alt="image" src="https://github.com/user-attachments/assets/0cae3bf6-c5a6-42a7-8877-1a1dc45bd22e">

具体信息：
System.ArgumentException: Bitmap must be of type Bgra8888. (Parameter 'bmp')
   at Sdcb.WordClouds.WordCloud.FillCache(SKBitmap bmp, HorizontalOrVertical textOrientations, Boolean[,] dest, SKRectI destRect)
   at Sdcb.WordClouds.WordCloud.FillAndUpdate(WordCloudOptions options, IntegralMap integralMap, Single fontSize, Boolean[,] cache, SKPaint fontPaintCache, PositionedTextGroup group, WordCloudContext ctx, OrientationRect orp)
   at Sdcb.WordClouds.WordCloud.CreateTextItem(WordCloudOptions options, Traverser traverser, IntegralMap integralMap, Single fontSize, Boolean[,] cache, SKPaint fontPaintCache, WordScore word)
   at Sdcb.WordClouds.WordCloud.<>c__DisplayClass19_0.<Create>b__0(WordScore word)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Sdcb.WordClouds.WordCloud.Create(WordCloudOptions options)
   at Program.<Main>$(String[] args) in /Users/lito/RiderProjects/WordCloudTest/WordCloudTest/Program.cs:line 5

**Comment by sdcb** [comment]
should fixed in 2.0.1 version.
